# Generated by Django 3.2 on 2021-05-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del Curso')),
                ('fecha_inicio', models.DateField(max_length=50, verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(max_length=50, verbose_name='Fecha de Finalización')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Profesor')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('cursos_id', models.ManyToManyField(to='cursos.Curso')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo de la Clase')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion de la Clase')),
                ('url_video', models.URLField(max_length=50, verbose_name='URL de la Clase')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Alumno')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('curso', models.ManyToManyField(to='cursos.Curso')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
