# Generated by Django 3.2.2 on 2021-05-08 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20210507_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='url_video',
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del Tema')),
                ('url_video', models.URLField(max_length=50, verbose_name='URL de la Clase')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.clases')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
    ]
